#!/bin/bash

HDMI_STATUS="$(cat /sys/class/drm/card0-HDMI-A-1/status)"

if [ "${HDMI_STATUS}" = connected ]; then
    pactl set-card-profile 0 output:hdmi-stereo
    notify-send -i computer -t 5000 "Notification" "HDMI connected"
else
    pactl set-card-profile 0 output:analog-stereo+input:analog-stereo
    notify-send -i computer -t 5000 "Notification" "HDMI disconnected"
fi

exit 0

